// DOM

const blocoA = document.querySelector('#btA')
const blocoB = document.querySelector('#btB')
const blocoC = document.querySelector('#btC')
const blocoD = document.querySelector('#btD')
const blocoE = document.querySelector('#btE')
const blocoF = document.querySelector('#btF')
const blocoG = document.querySelector('#btG')
const blocoH = document.querySelector('#btH')
const blocoI = document.querySelector('#btI')
const blocoJ = document.querySelector('#btJ')
const blocoK = document.querySelector('#btK')
const blocoL = document.querySelector('#btL')
const blocoM = document.querySelector('#btM')
const blocoN = document.querySelector('#btN')
const paragrafo = document.querySelector('#info')
const primeiraFoto = document.querySelector('#foto-1')
const segundaFoto = document.querySelector('#foto-2')
const terceiraFoto = document.querySelector('#foto-3')